//go:build go1.22

// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package main

import (
	"fmt"
	"net/http"
)

// Defines values for DeviceType.
const (
	CPU DeviceType = "CPU"
	GPU DeviceType = "GPU"
)

// Defines values for Role.
const (
	Assistant Role = "assistant"
	System    Role = "system"
	User      Role = "user"
)

// Defines values for Status.
const (
	BUSY     Status = "BUSY"
	DRAINING Status = "DRAINING"
	READY    Status = "READY"
)

// DeviceType defines model for DeviceType.
type DeviceType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Detail Human-readable details
	Detail string `json:"detail"`

	// Error Machine-readable error code
	Error string `json:"error"`
}

// HeartbeatRequest defines model for HeartbeatRequest.
type HeartbeatRequest struct {
	// EmaTps Exponential moving average tokens/sec (real or estimated)
	EmaTps      *float32 `json:"ema_tps"`
	InFlight    int      `json:"in_flight"`
	LastJobMs   *int     `json:"last_job_ms"`
	ServerId    string   `json:"server_id"`
	Status      Status   `json:"status"`
	TimestampMs int64    `json:"timestamp_ms"`
}

// Message defines model for Message.
type Message struct {
	Content string `json:"content"`
	Role    Role   `json:"role"`
}

// OkResponse defines model for OkResponse.
type OkResponse struct {
	Ok bool `json:"ok"`
}

// Output defines model for Output.
type Output struct {
	Content string `json:"content"`
	Role    Role   `json:"role"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// ContextLimit Optional max context length supported
	ContextLimit *int       `json:"context_limit"`
	DeviceType   DeviceType `json:"device_type"`

	// Endpoint Base URL of compute agent (not LMStudio)
	Endpoint       string   `json:"endpoint"`
	MaxConcurrency int      `json:"max_concurrency"`
	Models         []string `json:"models"`
	ServerId       string   `json:"server_id"`
	VramGb         *float32 `json:"vram_gb"`
}

// Role defines model for Role.
type Role string

// RouteRequest defines model for RouteRequest.
type RouteRequest struct {
	// EstimatedPromptTokens Optional; if omitted, router may approximate from chars
	EstimatedPromptTokens *int   `json:"estimated_prompt_tokens"`
	MaxTokens             int    `json:"max_tokens"`
	ModelId               string `json:"model_id"`
	PromptChars           int    `json:"prompt_chars"`

	// RequestId UUID generated by client (idempotency key)
	RequestId   string `json:"request_id"`
	TimestampMs int64  `json:"timestamp_ms"`
}

// RouteResponse defines model for RouteResponse.
type RouteResponse struct {
	// Endpoint Base URL of compute agent to call /run on
	Endpoint string `json:"endpoint"`

	// Reason Debug reason for routing choice (optional but useful)
	Reason    string `json:"reason"`
	RequestId string `json:"request_id"`
	ServerId  string `json:"server_id"`
}

// RunRequest defines model for RunRequest.
type RunRequest struct {
	MaxTokens   int       `json:"max_tokens"`
	Messages    []Message `json:"messages"`
	ModelId     string    `json:"model_id"`
	RequestId   string    `json:"request_id"`
	TimestampMs int64     `json:"timestamp_ms"`
}

// RunResponse defines model for RunResponse.
type RunResponse struct {
	// Cached Present and true if served from idempotency cache
	Cached    *bool  `json:"cached"`
	ModelId   string `json:"model_id"`
	Output    Output `json:"output"`
	RequestId string `json:"request_id"`
	Timing    Timing `json:"timing"`
	Usage     Usage  `json:"usage"`
}

// Status defines model for Status.
type Status string

// Timing defines model for Timing.
type Timing struct {
	ElapsedMs int `json:"elapsed_ms"`
}

// Usage defines model for Usage.
type Usage struct {
	CompletionTokens *int `json:"completion_tokens"`
	PromptTokens     *int `json:"prompt_tokens"`
	TotalTokens      *int `json:"total_tokens"`
}

// HeartbeatJSONRequestBody defines body for Heartbeat for application/json ContentType.
type HeartbeatJSONRequestBody = HeartbeatRequest

// RegisterComputeJSONRequestBody defines body for RegisterCompute for application/json ContentType.
type RegisterComputeJSONRequestBody = RegisterRequest

// RouteRequestJSONRequestBody defines body for RouteRequest for application/json ContentType.
type RouteRequestJSONRequestBody = RouteRequest

// RunCompletionJSONRequestBody defines body for RunCompletion for application/json ContentType.
type RunCompletionJSONRequestBody = RunRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Compute -> Router heartbeat (dynamic load)
	// (POST /heartbeat)
	Heartbeat(w http.ResponseWriter, r *http.Request)
	// Compute -> Router one-time registration (capabilities)
	// (POST /register)
	RegisterCompute(w http.ResponseWriter, r *http.Request)
	// Client -> Router route selection (metadata only)
	// (POST /route)
	RouteRequest(w http.ResponseWriter, r *http.Request)
	// Client -> Compute run (full request; non-streaming)
	// (POST /run)
	RunCompletion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Heartbeat operation middleware
func (siw *ServerInterfaceWrapper) Heartbeat(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Heartbeat(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterCompute operation middleware
func (siw *ServerInterfaceWrapper) RegisterCompute(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterCompute(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RouteRequest operation middleware
func (siw *ServerInterfaceWrapper) RouteRequest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RouteRequest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunCompletion operation middleware
func (siw *ServerInterfaceWrapper) RunCompletion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunCompletion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/heartbeat", wrapper.Heartbeat)
	m.HandleFunc("POST "+options.BaseURL+"/register", wrapper.RegisterCompute)
	m.HandleFunc("POST "+options.BaseURL+"/route", wrapper.RouteRequest)
	m.HandleFunc("POST "+options.BaseURL+"/run", wrapper.RunCompletion)

	return m
}
